// index.js

const mongoose = require('mongoose');
const Country = require('./src/model/countryModel'); // Nhập model Country

// Kết nối MongoDB (thay 'your-mongodb-uri' bằng URI MongoDB của bạn)
mongoose.connect('mongodb://localhost:27017/price_db', { useNewUrlParser: true, useUnifiedTopology: true })
    .then(() => {
        console.log('Connected to MongoDB');
    })
    .catch(err => {
        console.log('Error connecting to MongoDB', err);
    });

// Thêm một số quốc gia vào cơ sở dữ liệu
const countries = [
    { name: 'Afghanistan', flag: '🇦🇫', code: 'AF' },
    { name: 'Albania', flag: '🇦🇱', code: 'AL' },
    { name: 'Algeria', flag: '🇩🇿', code: 'DZ' },
    { name: 'Andorra', flag: '🇦🇩', code: 'AD' },
    { name: 'Angola', flag: '🇦🇴', code: 'AO' },
    { name: 'Antigua and Barbuda', flag: '🇦🇬', code: 'AG' },
    { name: 'Argentina', flag: '🇦🇷', code: 'AR' },
    { name: 'Armenia', flag: '🇦🇲', code: 'AM' },
    { name: 'Australia', flag: '🇦🇺', code: 'AU' },
    { name: 'Austria', flag: '🇦🇹', code: 'AT' },
    { name: 'Azerbaijan', flag: '🇦🇿', code: 'AZ' },
    { name: 'Bahamas', flag: '🇧🇸', code: 'BS' },
    { name: 'Bahrain', flag: '🇧🇭', code: 'BH' },
    { name: 'Bangladesh', flag: '🇧🇩', code: 'BD' },
    { name: 'Barbados', flag: '🇧🇧', code: 'BB' },
    { name: 'Belarus', flag: '🇧🇾', code: 'BY' },
    { name: 'Belgium', flag: '🇧🇪', code: 'BE' },
    { name: 'Belize', flag: '🇧🇿', code: 'BZ' },
    { name: 'Benin', flag: '🇧🇯', code: 'BJ' },
    { name: 'Bhutan', flag: '🇧🇹', code: 'BT' },
    { name: 'Bolivia', flag: '🇧🇴', code: 'BO' },
    { name: 'Bosnia and Herzegovina', flag: '🇧🇦', code: 'BA' },
    { name: 'Botswana', flag: '🇧🇼', code: 'BW' },
    { name: 'Brazil', flag: '🇧🇷', code: 'BR' },
    { name: 'Brunei', flag: '🇧🇳', code: 'BN' },
    { name: 'Bulgaria', flag: '🇧🇬', code: 'BG' },
    { name: 'Burkina Faso', flag: '🇧🇫', code: 'BF' },
    { name: 'Burundi', flag: '🇧🇮', code: 'BI' },
    { name: 'Cabo Verde', flag: '🇨🇻', code: 'CV' },
    { name: 'Cambodia', flag: '🇰🇭', code: 'KH' },
    { name: 'Cameroon', flag: '🇨🇲', code: 'CM' },
    { name: 'Canada', flag: '🇨🇦', code: 'CA' },
    { name: 'Central African Republic', flag: '🇨🇫', code: 'CF' },
    { name: 'Chad', flag: '🇹🇩', code: 'TD' },
    { name: 'Chile', flag: '🇨🇱', code: 'CL' },
    { name: 'China', flag: '🇨🇳', code: 'CN' },
    { name: 'Colombia', flag: '🇨🇴', code: 'CO' },
    { name: 'Comoros', flag: '🇰🇲', code: 'KM' },
    { name: 'Congo (Congo-Brazzaville)', flag: '🇨🇬', code: 'CG' },
    { name: 'Congo (Democratic Republic)', flag: '🇨🇩', code: 'CD' },
    { name: 'Costa Rica', flag: '🇨🇷', code: 'CR' },
    { name: 'Croatia', flag: '🇭🇷', code: 'HR' },
    { name: 'Cuba', flag: '🇨🇺', code: 'CU' },
    { name: 'Cyprus', flag: '🇨🇾', code: 'CY' },
    { name: 'Czech Republic (Czechia)', flag: '🇨🇿', code: 'CZ' },
    { name: 'Denmark', flag: '🇩🇰', code: 'DK' },
    { name: 'Djibouti', flag: '🇩🇯', code: 'DJ' },
    { name: 'Dominica', flag: '🇩🇲', code: 'DM' },
    { name: 'Dominican Republic', flag: '🇩🇴', code: 'DO' },
    { name: 'Ecuador', flag: '🇪🇨', code: 'EC' },
    { name: 'Egypt', flag: '🇪🇬', code: 'EG' },
    { name: 'El Salvador', flag: '🇸🇻', code: 'SV' },
    { name: 'Equatorial Guinea', flag: '🇬🇶', code: 'GQ' },
    { name: 'Eritrea', flag: '🇪🇷', code: 'ER' },
    { name: 'Estonia', flag: '🇪🇪', code: 'EE' },
    { name: 'Eswatini', flag: '🇸🇿', code: 'SZ' },
    { name: 'Ethiopia', flag: '🇪🇹', code: 'ET' },
    { name: 'Fiji', flag: '🇫🇯', code: 'FJ' },
    { name: 'Finland', flag: '🇫🇮', code: 'FI' },
    { name: 'France', flag: '🇫🇷', code: 'FR' },
    { name: 'Gabon', flag: '🇬🇦', code: 'GA' },
    { name: 'Gambia', flag: '🇬🇲', code: 'GM' },
    { name: 'Georgia', flag: '🇬🇪', code: 'GE' },
    { name: 'Germany', flag: '🇩🇪', code: 'DE' },
    { name: 'Ghana', flag: '🇬🇭', code: 'GH' },
    { name: 'Greece', flag: '🇬🇷', code: 'GR' },
    { name: 'Grenada', flag: '🇬🇩', code: 'GD' },
    { name: 'Guatemala', flag: '🇬🇹', code: 'GT' },
    { name: 'Guinea', flag: '🇬🇳', code: 'GN' },
    { name: 'Guinea-Bissau', flag: '🇬🇼', code: 'GW' },
    { name: 'Guyana', flag: '🇬🇾', code: 'GY' },
    { name: 'Haiti', flag: '🇭🇹', code: 'HT' },
    { name: 'Honduras', flag: '🇭🇳', code: 'HN' },
    { name: 'Hungary', flag: '🇭🇺', code: 'HU' },
    { name: 'Iceland', flag: '🇮🇸', code: 'IS' },
    { name: 'India', flag: '🇮🇳', code: 'IN' },
    { name: 'Indonesia', flag: '🇮🇩', code: 'ID' },
    { name: 'Iran', flag: '🇮🇷', code: 'IR' },
    { name: 'Iraq', flag: '🇮🇶', code: 'IQ' },
    { name: 'Ireland', flag: '🇮🇪', code: 'IE' },
    { name: 'Israel', flag: '🇮🇱', code: 'IL' },
    { name: 'Italy', flag: '🇮🇹', code: 'IT' },
    { name: 'Jamaica', flag: '🇯🇲', code: 'JM' },
    { name: 'Japan', flag: '🇯🇵', code: 'JP' },
    { name: 'Jordan', flag: '🇯🇴', code: 'JO' },
    { name: 'Kazakhstan', flag: '🇰🇿', code: 'KZ' },
    { name: 'Kenya', flag: '🇰🇪', code: 'KE' },
    { name: 'Kiribati', flag: '🇰🇮', code: 'KI' },
    { name: 'Korea, North', flag: '🇰🇵', code: 'KP' },
    { name: 'Korea, South', flag: '🇰🇷', code: 'KR' },
    { name: 'Kuwait', flag: '🇰🇼', code: 'KW' },
    { name: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG' },
    { name: 'Laos', flag: '🇱🇸', code: 'LA' },
    { name: 'Latvia', flag: '🇱🇻', code: 'LV' },
    { name: 'Lebanon', flag: '🇱🇧', code: 'LB' },
    { name: 'Lesotho', flag: '🇱🇸', code: 'LS' },
    { name: 'Liberia', flag: '🇱🇸', code: 'LR' },
    { name: 'Libya', flag: '🇱🇾', code: 'LY' },
    { name: 'Liechtenstein', flag: '🇱🇮', code: 'LI' },
    { name: 'Lithuania', flag: '🇱🇹', code: 'LT' },
    { name: 'Luxembourg', flag: '🇱🇺', code: 'LU' },
    { name: 'Madagascar', flag: '🇲🇬', code: 'MG' },
    { name: 'Malawi', flag: '🇲🇼', code: 'MW' },
    { name: 'Malaysia', flag: '🇲🇾', code: 'MY' },
    { name: 'Maldives', flag: '🇲🇻', code: 'MV' },
    { name: 'Mali', flag: '🇲🇱', code: 'ML' },
    { name: 'Malta', flag: '🇲🇹', code: 'MT' },
    { name: 'Marshall Islands', flag: '🇲🇭', code: 'MH' },
    { name: 'Mauritania', flag: '🇲🇷', code: 'MR' },
    { name: 'Mauritius', flag: '🇲🇺', code: 'MU' },
    { name: 'Mexico', flag: '🇲🇽', code: 'MX' },
    { name: 'Micronesia', flag: '🇫🇲', code: 'FM' },
    { name: 'Moldova', flag: '🇲🇩', code: 'MD' },
    { name: 'Monaco', flag: '🇲🇨', code: 'MC' },
    { name: 'Mongolia', flag: '🇲🇳', code: 'MN' },
    { name: 'Montenegro', flag: '🇲🇪', code: 'ME' },
    { name: 'Morocco', flag: '🇲🇦', code: 'MA' },
    { name: 'Mozambique', flag: '🇲🇿', code: 'MZ' },
    { name: 'Myanmar', flag: '🇲🇲', code: 'MM' },
    { name: 'Namibia', flag: '🇳🇦', code: 'NA' },
    { name: 'Nauru', flag: '🇳🇷', code: 'NR' },
    { name: 'Nepal', flag: '🇳🇵', code: 'NP' },
    { name: 'Netherlands', flag: '🇳🇱', code: 'NL' },
    { name: 'New Zealand', flag: '🇳🇿', code: 'NZ' },
    { name: 'Nicaragua', flag: '🇳🇮', code: 'NI' },
    { name: 'Niger', flag: '🇳🇬', code: 'NE' },
    { name: 'Nigeria', flag: '🇳🇬', code: 'NG' },
    { name: 'North Macedonia', flag: '🇲🇰', code: 'MK' },
    { name: 'Norway', flag: '🇳🇴', code: 'NO' },
    { name: 'Oman', flag: '🇴🇲', code: 'OM' },
    { name: 'Pakistan', flag: '🇵🇰', code: 'PK' },
    { name: 'Palau', flag: '🇵🇼', code: 'PW' },
    { name: 'Panama', flag: '🇵🇦', code: 'PA' },
    { name: 'Papua New Guinea', flag: '🇵🇬', code: 'PG' },
    { name: 'Paraguay', flag: '🇵🇾', code: 'PY' },
    { name: 'Peru', flag: '🇵🇪', code: 'PE' },
    { name: 'Philippines', flag: '🇵🇭', code: 'PH' },
    { name: 'Poland', flag: '🇵🇱', code: 'PL' },
    { name: 'Portugal', flag: '🇵🇹', code: 'PT' },
    { name: 'Qatar', flag: '🇶🇦', code: 'QA' },
    { name: 'Romania', flag: '🇷🇴', code: 'RO' },
    { name: 'Russia', flag: '🇷🇺', code: 'RU' },
    { name: 'Rwanda', flag: '🇷🇼', code: 'RW' },
    { name: 'Saint Kitts and Nevis', flag: '🇰🇳', code: 'KN' },
    { name: 'Saint Lucia', flag: '🇱🇨', code: 'LC' },
    { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', code: 'VC' },
    { name: 'Samoa', flag: '🇼🇸', code: 'WS' },
    { name: 'San Marino', flag: '🇸🇲', code: 'SM' },
    { name: 'Sao Tome and Principe', flag: '🇸🇹', code: 'ST' },
    { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA' },
    { name: 'Senegal', flag: '🇸🇳', code: 'SN' },
    { name: 'Serbia', flag: '🇷🇸', code: 'RS' },
    { name: 'Seychelles', flag: '🇸🇨', code: 'SC' },
    { name: 'Sierra Leone', flag: '🇸🇱', code: 'SL' },
    { name: 'Singapore', flag: '🇸🇬', code: 'SG' },
    { name: 'Slovakia', flag: '🇸🇰', code: 'SK' },
    { name: 'Slovenia', flag: '🇸🇮', code: 'SI' },
    { name: 'Solomon Islands', flag: '🇸🇧', code: 'SB' },
    { name: 'Somalia', flag: '🇸🇴', code: 'SO' },
    { name: 'South Africa', flag: '🇿🇦', code: 'ZA' },
    { name: 'South Sudan', flag: '🇸🇸', code: 'SS' },
    { name: 'Spain', flag: '🇪🇸', code: 'ES' },
    { name: 'Sri Lanka', flag: '🇱🇰', code: 'LK' },
    { name: 'Sudan', flag: '🇸🇩', code: 'SD' },
    { name: 'Suriname', flag: '🇸🇷', code: 'SR' },
    { name: 'Sweden', flag: '🇸🇪', code: 'SE' },
    { name: 'Switzerland', flag: '🇨🇭', code: 'CH' },
    { name: 'Syria', flag: '🇸🇾', code: 'SY' },
    { name: 'Taiwan', flag: '🇹🇼', code: 'TW' },
    { name: 'Tajikistan', flag: '🇹🇯', code: 'TJ' },
    { name: 'Tanzania', flag: '🇹🇿', code: 'TZ' },
    { name: 'Thailand', flag: '🇹🇭', code: 'TH' },
    { name: 'Togo', flag: '🇹🇬', code: 'TG' },
    { name: 'Tonga', flag: '🇹🇴', code: 'TO' },
    { name: 'Trinidad and Tobago', flag: '🇹🇹', code: 'TT' },
    { name: 'Tunisia', flag: '🇹🇳', code: 'TN' },
    { name: 'Turkey', flag: '🇹🇷', code: 'TR' },
    { name: 'Turkmenistan', flag: '🇹🇲', code: 'TM' },
    { name: 'Tuvalu', flag: '🇹🇻', code: 'TV' },
    { name: 'Uganda', flag: '🇺🇬', code: 'UG' },
    { name: 'Ukraine', flag: '🇺🇦', code: 'UA' },
    { name: 'United Arab Emirates', flag: '🇦🇪', code: 'AE' },
    { name: 'United Kingdom', flag: '🇬🇧', code: 'GB' },
    { name: 'United States', flag: '🇺🇸', code: 'US' },
    { name: 'Uruguay', flag: '🇺🇾', code: 'UY' },
    { name: 'Uzbekistan', flag: '🇺🇿', code: 'UZ' },
    { name: 'Vanuatu', flag: '🇻🇺', code: 'VU' },
    { name: 'Vatican City', flag: '🇻🇦', code: 'VA' },
    { name: 'Venezuela', flag: '🇻🇪', code: 'VE' },
    { name: 'Vietnam', flag: '🇻🇳', code: 'VN' },
    { name: 'Yemen', flag: '🇾🇪', code: 'YE' },
    { name: 'Zambia', flag: '🇿🇲', code: 'ZM' },
    { name: 'Zimbabwe', flag: '🇿🇼', code: 'ZW' },
];


// Lưu các quốc gia vào MongoDB
Country.insertMany(countries)
    .then(docs => {
        console.log('Countries added:', docs);
    })
    .catch(err => {
        console.log('Error adding countries:', err);
    });
